@startuml

title Customer Oriented Operational Scenario (CONOPS) - Притулок "Добрий Дім"

|Притулок|
start

:Прийом оголошень про тварин;
note right
    Мета: Розміщення оголошень про тварин з метою їх усиновлення.
    Обмеження: Велика кількість тварин потребує швидкого та ефективного розміщення оголошень.
    Дії: Прийом та перевірка оголошень від користувачів, забезпечення швидкого та простого процесу.
end note

:Розміщення оголошень про тварин;
note right
    Мета: Забезпечити доступність та оголошення для потенційних власників.
    Обмеження: Недостатність інформації може знизити зацікавленість власників.
    Дії: Публікація детальної інформації та зображень про тварин, залучення уваги власників.
end note

:Відповідь на запити користувачів;
note right
    Мета: Забезпечити потенційним власникам відповідну підтримку та інформацію.
    Обмеження: Затримки у відповіді можуть призвести до втрати зацікавленості власників.
    Дії: Швидка реакція та висока якість відповіді на запити користувачів.
end note

:Контакт зі знайомством;
note right
    Мета: Забезпечити позитивне враження від контакту з притулком.
    Обмеження: Втрата контакту може призвести до втрати зацікавленості власників.
    Дії: Створення дружнього та позитивного середовища для спілкування з потенційними власниками.
end note

:Передача тварини новому власнику;
note right
    Мета: Забезпечити успішну адаптацію тварин та їх власників.
    Обмеження: Відсутність підтримки після усиновлення може призвести до проблем.
    Дії: Надання підтримки та порад після усиновлення, відслідковування долі тварин.
end note

stop

@enduml
