@startuml

' Назва процесу
title Усиновлення тварини

' Початок процесу
start

' Вхідна подія: Користувач відвідує сайт
: Користувач відвідує сайт;
: Пошук тварини;

' Активності
: Перегляд оголошень;
: Вибір тварини для усиновлення;
: Заповнення заявки на усиновлення;

' Вхідна подія: Притулок отримує заявку на усиновлення
: Притулок отримує заявку на усиновлення;

' Виключення: Тварина вже була усиновлена
if (Тварина вже усиновлена?) then (Так)
  : Повідомлення користувачу про недоступність тварини;
else (Ні)
  : Підтвердження заявки та назначення зустрічі;
endif

' Активності
: Зустріч з потенційним усиновлювачем;
: Підписання угоди про усиновлення;

' Вхідна подія: Усиновлення успішно завершено
: Тварина успішно усиновлена;

' Кінець процесу
stop

@enduml
