@startuml
title Animal Adoption Advertisement Process
left to right direction
skinparam packageStyle rectangle

actor Shelter as S
rectangle  {
  [Create Advertisement] --> [Add Photo and Information]
  [Add Photo and Information] --> [Post Advertisement]
  [Post Advertisement] --> [Check Availability]
}
S --> [Create Advertisement]
@enduml
