@startuml
left to right direction
skinparam rectangle {
    BorderColor black
    BackgroundColor lightgrey
}

rectangle "Lean Canvas" {


      Problems : 1. Велика кількість безпритульних тварин, які потребують нових домівок.\n
      Problems : 2. Низька обізнаність людей про можливості усиновлення тварин.
      Problems : 3. Складність процесу пошуку та контактування з притулками для тварин.


    CustomerSegments : 1. Люди, які бажають усиновити тварину.
    CustomerSegments : 2. Притулки для тварин, що шукають власників для своїх підопічних.
    CustomerSegments : 3. Волонтери та організації, що займаються порятунком тварин.


    UVP : 1. Єдина платформа, що об’єднує людей та притулки, спрощуючи процес усиновлення тварин.
    UVP : 2. Зручний та швидкий пошук тварин за різними критеріями.
    UVP : 3. Можливість безпосереднього контакту з притулками через сайт.


    Solution : 1. Розробка інтуїтивно зрозумілого інтерфейсу для розміщення та перегляду оголошень.
    Solution : 2. Впровадження функції пошуку тварин за різними параметрами (вік, порода, розмір тощо).
    Solution : 3. Автоматизація процесу сповіщень та відповіді на запити.


    Channels : 1. Соціальні мережі (Facebook, Instagram, Twitter).
    Channels : 2. Партнерство з притулками та волонтерськими організаціями.
    Channels : 3. Онлайн реклама (Google Ads, соціальні мережі).
    Channels : 4. Сарафанне радіо та PR-кампанії.


    RevenueStreams : 1. Рекламні банери на сайті.
    RevenueStreams : 2. Платні преміум-об'яви для притулків.
    RevenueStreams : 3. Пожертвування від користувачів та організацій.
    RevenueStreams : 4. Партнерські програми з ветеринарними клініками та магазинами для тварин.


    KeyMetrics : 1. Кількість успішних усиновлень через сайт.
    KeyMetrics : 2. Кількість активних користувачів та притулків на платформі.
    KeyMetrics : 3. Трафік на сайті (кількість відвідувачів).
    KeyMetrics : 4. Рівень задоволеності користувачів (відгуки та оцінки).


    CostStructure : 1. Розробка та підтримка вебсайту.
    CostStructure : 2. Маркетинг та рекламні кампанії.
    CostStructure : 3. Зарплати співробітникам (розробники, маркетологи, підтримка клієнтів).
    CostStructure : 4. Витрати на хостинг та доменне ім'я.


    UnfairAdvantage : 1. Інноваційний підхід до проблеми усиновлення тварин.
    UnfairAdvantage : 2. Широка база даних тварин та інтеграція з притулками.
    UnfairAdvantage : 3. Зручний та простий у використанні інтерфейс.
    UnfairAdvantage : 4. Сильна соціальна місія, що привертає підтримку спільноти та волонтерів.

}
@enduml
