spring:
  application:
    name: marketplace

  profiles:
    active: prod


    spring.jpa.show-sql=true
    spring.flyway.baseline-on-migrate=true
    spring.jpa.hibernate.ddl-auto=validate


jpa:
  show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true