spring:
  application:
    name: marketplace
  datasource:
    hikari:
      maximum-pool-size: 10 # Adjust based on your load
  servlet:
    multipart:
      max-file-size: 10MB # Adjust based on your needs
      max-request-size: 10MB # Adjust based on your needs

  profiles:
    active: local



  #Jwt properties
  jwt:
    secret-key: this is very secret string for best security
    token-prefix: Bearer
    token-expiration-after-days: 14