spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/marketplace
    username: postgres
    password: password

file:
  #windows
  #upload-dir: E:\\JavaProjects\\team-challenge\\photo
  #ubuntu
  upload-dir: /home/chak/projects/java/teamchallenge/photo
