@startuml
|Притулок|
start
:Прийом оголошень про тварин;
note right
    Емоції: Розгубленість\n
    Проблеми: Обробка великої кількості оголошень\n
    Можливості: Використання систем автоматизації
end note

:Розміщення оголошень про тварин;
note right
    Емоції: Відповідальність\n
    Проблеми: Відсутність відгуків від потенційних власників\n
    Можливості: Стимулювання зворотного зв'язку
end note

:Відповідь на запити користувачів;
note right
    Емоції: Важливість\n
    Проблеми: Затримки у відповіді\n
    Можливості: Швидка реакція та підтримка
end note

:Контакт зі знайомством;
note right
    Емоції: Надія\n
    Проблеми: Неочікуваний вихід\n
    Можливості: Посилення співпраці та взаємодії
end note

:Передача тварини новому власнику;
note right
    Емоції: Задоволення\n
    Проблеми: Відслідковування долі тварин\n
    Можливості: Система моніторингу після усиновлення
end note
stop
@enduml
