@startuml
|Клієнт|
start
:Пошук тварини;
:Відвідує сайт;
note right
    Емоції: Зацікавлення\n
    Проблеми: Складність навігації\n
    Можливості: Покращення UX
end note

:Перегляд оголошень;
note right
    Емоції: Захоплення\n
    Проблеми: Недостатньо інформації\n
    Можливості: Додати детальні описи
end note

:Зв'язок з розміщувачем;
note right
Емоції: Хвилювання\n
Проблеми: Відсутність швидкої відповіді\n
Можливості: Налаштування авто-відповідей
end note

:Усиновлення тварини;
note right
Емоції: Радість\n
Проблеми: Складний процес\n
Можливості: Спрощення процесу усиновлення
end note

:Догляд за твариною;
note right
Емоції: Задоволення\n
Проблеми: Відсутність підтримки\n
Можливості: Створення служби підтримки
end note
stop
@enduml