@startuml
|Користувач|
start
:Вхід на сайт;
note right
    Емоції: Зацікавлення\n
    Проблеми: Складність навігації\n
    Можливості: Покращення UX
end note

:Розміщення оголошення про тварину;
note right
    Емоції: Сподівання\n
    Проблеми: Складність вибору платформи\n
    Можливості: Використання рекомендацій друзів
end note

:Очікування відгуків від потенційних власників;
note right
    Емоції: Нетерплячість\n
    Проблеми: Відсутність зворотного зв'язку\n
    Можливості: Залучення учасників груп спільностей
end note

:Вибір потенційного власника тварини;
note right
    Емоції: Сподівання\n
    Проблеми: Недовіра до потенційних власників\n
    Можливості: Перевірка рекомендацій та інформації в профілях
end note

:Передача тварини новому власнику;
note right
    Емоції: Задоволення\n
    Проблеми: Відслідковування долі тварин\n
    Можливості: Система моніторингу після усиновлення
end note
stop
@enduml
