@startuml
class User {
  Long id
  String email
  String password
  String userType
  String name
  String profilePicture
  String contactInfo
  Date createdAt
  Date updatedAt
  +createUser()
  +updateUser()
  +deleteUser()
  +getUserDetails()
}

class Shelter extends User {
  String shelterName
  String address
  String phone
  String website
  +publishAd()
  +editAd()
  +deleteAd()
}

class Individual extends User {
  String adoptionPreferences
  List<Ad> favoriteAds
  +searchForPets()
  +addAd()
  +editAd()
  +deleteAd()
  +addToFavorites()
}

class Ad {
  Long id
  String title
  List<Photo> photos
  int age
  String size
  String color
  String address
  String petName
  String gender
  String description
  String furLength
  String health
  Category category
  Date createdAt
  Date updatedAt
  +createAd()
  +updateAd()
  +deleteAd()
  +getAdDetails()
}

class Category {
  Long id
  String name
  +createCategory()
  +updateCategory()
  +deleteCategory()
}

class Photo {
  Long id
  String url
  boolean isMainPhoto
  Long adId
  +uploadPhoto()
  +deletePhoto()
  +setAsMainPhoto()
}

class Favorite {
  Long id
  Long userId
  Long adId
  +addToFavorites()
  +removeFromFavorites()
  +getUserFavorites()
}

class Comment {
  Long id
  Long userId
  Long adId
  String content
  Date createdAt
  Date updatedAt
  +addComment()
  +editComment()
  +deleteComment()
}

class History {
  Long id
  Long userId
  Long adId
  String story
  Date createdAt
  +addStory()
  +getStory()
}

User <|-- Shelter
User <|-- Individual
Ad "1" -- "*" Photo
Ad "1" -- "1" Category
User "1" -- "*" Ad
Individual "1" -- "*" Favorite
Ad "1" -- "*" Comment
User "1" -- "*" History
@enduml
