@startuml
title Backlog - Притулок "Добрий Дім"
note as organ
| Номер | Тип користувача | Історія користувача |
|-------|------------------|---------------------|
| PD-001 | Притулок "Добрий Дім" | Як притулок, я хочу мати можливість приймати оголошення про тварин, щоб забезпечити їм швидке усиновлення. |
| PD-002 | Притулок "Добрий Дім" | Як притулок, я хочу мати систему розміщення оголошень, щоб забезпечити зручний процес роботи з користувачами. |
| PD-003 | Притулок "Добрий Дім" | Як притулок, я хочу мати можливість відповідати на запити користувачів швидко та ефективно, щоб забезпечити їхню задоволеність. |
| PD-004 | Притулок "Добрий Дім" | Як притулок, я хочу мати можливість відслідковувати статус тварин після усиновлення, щоб забезпечити їхню долю. |
| PD-005 | Притулок "Добрий Дім" | Як притулок, я хочу мати систему підтримки, щоб надавати допомогу власникам тварин після усиновлення. |
| OP-001 | Ольга Петренко | Як Ольга, я хочу мати можливість легко розмістити оголошення про тварину, щоб знайти їй новий дім. |
| OP-002 | Ольга Петренко | Як Ольга, я хочу мати можливість швидко знайти зацікавлених людей, які хочуть усиновити тварину, щоб забезпечити їй найкращі умови. |
| OP-003 | Ольга Петренко | Як Ольга, я хочу мати можливість перевіряти відповідальність потенційних власників, щоб бути впевненою в майбутній долі тварини. |
| OP-004 | Ольга Петренко | Як Ольга, я хочу мати можливість отримувати швидкий зворотний зв'язок від потенційних власників, щоб ефективно комунікувати з ними. |
| OP-005 | Ольга Петренко | Як Ольга, я хочу мати доступ до підтримки після усиновлення тварини, щоб надати їй належну догляд та підтримку. |
| UC-001 | Користувач, що шукає тварину | Як користувач, я хочу мати зручний інтерфейс для пошуку тварини за різними критеріями, щоб знайти ідеального усиновлювача. |
| UC-002 | Користувач, що шукає тварину | Як користувач, я хочу мати можливість зберігати обрані тварини у списку "Обране", щоб зручно повертатися до них пізніше та порівнювати. |
end note
@enduml
